lsコマンドを作る1
ckym02/ruby-practices pull request #4
Opened 2023-01-07 02:48 UTC by koyama-c

## 概要
オプションなしのlsコマンドの実装を行いました。

## 動作確認
rubyプログラムとlsコマンド実行時の比較
```
~/Desktop/ruby-practices/04.ls feature/ls1*
❯ ruby ls1.rb
ls1.rb
~/Desktop/ruby-practices/04.ls feature/ls1*
❯ ls
ls1.rb

~/Desktop/ruby-practices/04.ls feature/ls1*
❯ ruby ls1.rb .
ls1.rb
~/Desktop/ruby-practices/04.ls feature/ls1*
❯ ls .
ls1.rb

~/Desktop/ruby-practices/04.ls feature/ls1*
❯ ruby ls1.rb ~/Desktop/ruby-practices/
00.hoge.txt                              05.wc              Gemfile.lock
00.hogepiyohogepiyohogepiyohogepiyo.txt  06.bowling_object  README.md
01.fizzbuzz                              07.ls_object       あいうえお.txt
02.calendar                              98.rake            アイウエオ.txt
03.bowling                               99.wc_object
04.ls                                    Gemfile

~/Desktop/ruby-practices/04.ls feature/ls1*
❯ ls ~/Desktop/ruby-practices/04.ls
ls1.rb

~/Desktop/ruby-practices/04.ls feature/ls1*
❯ ls ~/Desktop/ruby-practices/
00.hoge.txt                             05.wc                                   Gemfile.lock
00.hogepiyohogepiyohogepiyohogepiyo.txt 06.bowling_object                       README.md
01.fizzbuzz                             07.ls_object                            あいうえお.txt
02.calendar                             98.rake                                 アイウエオ.txt
03.bowling                              99.wc_object
04.ls                                   Gemfile
```
rubocopが全てパスしていること
```
~/Desktop/ruby-practices/04.ls feature/ls1*
❯ rubocop
Inspecting 1 file
.

1 file inspected, no offenses detected
```

2023-01-12 15:37 UTC, u1tnk requested changes

2023-01-12 15:37 UTC, u1tnk commented on 04.ls/ls1.rb
> +  (files.length % num).zero? ? files.length / num : files.length / num + 1
これは最近入ったので知らなくて当然ですが、 [Ruby 3.2 - Integer / Set](https://zenn.dev/tmtms/articles/202212-ruby32-18#integer%23ceildiv-%E8%BF%BD%E5%8A%A0) こちらを使うと簡単なので共有しておきます。
ruby3.2からのものなのでバージョンに注意です。

2023-01-12 15:37 UTC, u1tnk commented on 04.ls/ls1.rb
> +def swap_rows_and_columns(num, files)
こちらはほぼ同じ機能のメソッドが Arrayにあるので見てみてください。

2023-01-15 06:13 UTC, koyama-c commented
@u1tnk 
レビューいただきありがとうございます。
ご指摘いただいた箇所と追加で以下のように追加修正しました。ご確認いただけますと幸いです。

- 引数に複数の任意のファイルやディレクトリを指定できる
- 引数がない場合はカレントディレクトリのファイル一覧が表示される
- 該当のファイルがないとエラーメッセージを表示する

2023-01-15 06:14 UTC, koyama-c commented on 04.ls/ls1.rb
> +  (files.length % num).zero? ? files.length / num : files.length / num + 1
知りませんでした..勉強になります！

2023-01-15 06:17 UTC, koyama-c commented on 04.ls/ls1.rb
> +def swap_rows_and_columns(num, files)
Arrayのtransposeメソッドですね。同じようなものをわざわざ実装する必要なかったですね..
こちらを使用して実装するよう修正しました。

2023-01-15 14:23 UTC, u1tnk approved these changes

2023-01-19 23:00 UTC, merged