lsコマンドを作る3
ckym02/ruby-practices pull request #6
Opened 2023-01-25 13:17 UTC by koyama-c

## 概要
https://bootcamp.fjord.jp/practices/223
-rオプションが使えるlsコマンドの実装。

## rubyプログラムで実行とlsコマンドで実行した結果の比較
```
# 引数なし（rオプションのみ）
~/Desktop/ruby-practices feature/ls3*
❯ ls -r
アイウエオ.txt                          99.wc_object                            03.bowling
あいうえお.txt                          98.rake                                 02.calendar
aAあア.txt                              07.ls_object                            01.fizzbuzz
README.md                               06.bowling_object                       00.hogepiyohogepiyohogepiyohogepiyo.txt
Gemfile.lock                            05.wc                                   00.hoge.txt
Gemfile                                 04.ls

~/Desktop/ruby-practices feature/ls3*
❯ ruby 04.ls/ls.rb -r
アイウエオ.txt  99.wc_object       03.bowling
あいうえお.txt  98.rake            02.calendar
aAあア.txt      07.ls_object       01.fizzbuzz
README.md       06.bowling_object  00.hogepiyohogepiyohogepiyohogepiyo.txt
Gemfile.lock    05.wc              00.hoge.txt
Gemfile         04.ls

# 引数なし（rオプションとaオプション）
~/Desktop/ruby-practices feature/ls3*
❯ ls -ar
アイウエオ.txt                          07.ls_object                            00.hoge.txt
あいうえお.txt                          06.bowling_object                       .rubocop.yml
aAあア.txt                              05.wc                                   .gitignore
README.md                               04.ls                                   .git
Gemfile.lock                            03.bowling                              ..
Gemfile                                 02.calendar                             .
99.wc_object                            01.fizzbuzz
98.rake                                 00.hogepiyohogepiyohogepiyohogepiyo.txt

~/Desktop/ruby-practices feature/ls3*
❯ ruby 04.ls/ls.rb -ar
アイウエオ.txt  98.rake            01.fizzbuzz
あいうえお.txt  07.ls_object       00.hogepiyohogepiyohogepiyohogepiyo.txt
aAあア.txt      06.bowling_object  00.hoge.txt
README.md       05.wc              .rubocop.yml
Gemfile.lock    04.ls              .gitignore
Gemfile         03.bowling         .git
99.wc_object    02.calendar

# 任意のディレクトリを複数引数に渡す（rオプションとaオプション）
~/Desktop/ruby-practices feature/ls3*
❯ ls -ra ~/Desktop/ruby-practices .
/Users/koyama/Desktop/ruby-practices:
アイウエオ.txt                          07.ls_object                            00.hoge.txt
あいうえお.txt                          06.bowling_object                       .rubocop.yml
aAあア.txt                              05.wc                                   .gitignore
README.md                               04.ls                                   .git
Gemfile.lock                            03.bowling                              ..
Gemfile                                 02.calendar                             .
99.wc_object                            01.fizzbuzz
98.rake                                 00.hogepiyohogepiyohogepiyohogepiyo.txt

.:
アイウエオ.txt                          07.ls_object                            00.hoge.txt
あいうえお.txt                          06.bowling_object                       .rubocop.yml
aAあア.txt                              05.wc                                   .gitignore
README.md                               04.ls                                   .git
Gemfile.lock                            03.bowling                              ..
Gemfile                                 02.calendar                             .
99.wc_object                            01.fizzbuzz
98.rake                                 00.hogepiyohogepiyohogepiyohogepiyo.txt

~/Desktop/ruby-practices feature/ls3*
❯ ruby 04.ls/ls.rb -ra ~/Desktop/ruby-practices .
/Users/koyama/Desktop/ruby-practices:
アイウエオ.txt  98.rake            01.fizzbuzz
あいうえお.txt  07.ls_object       00.hogepiyohogepiyohogepiyohogepiyo.txt
aAあア.txt      06.bowling_object  00.hoge.txt
README.md       05.wc              .rubocop.yml
Gemfile.lock    04.ls              .gitignore
Gemfile         03.bowling         .git
99.wc_object    02.calendar

.:
アイウエオ.txt  98.rake            01.fizzbuzz
あいうえお.txt  07.ls_object       00.hogepiyohogepiyohogepiyohogepiyo.txt
aAあア.txt      06.bowling_object  00.hoge.txt
README.md       05.wc              .rubocop.yml
Gemfile.lock    04.ls              .gitignore
Gemfile         03.bowling         .git
99.wc_object    02.calendar

# 任意のディレクトリとファイルを複数引数に渡す（rオプションとaオプション）
~/Desktop/ruby-practices feature/ls3*
❯ ls -ra アイウエオ.txt .
アイウエオ.txt

.:
アイウエオ.txt                          07.ls_object                            00.hoge.txt
あいうえお.txt                          06.bowling_object                       .rubocop.yml
aAあア.txt                              05.wc                                   .gitignore
README.md                               04.ls                                   .git
Gemfile.lock                            03.bowling                              ..
Gemfile                                 02.calendar                             .
99.wc_object                            01.fizzbuzz
98.rake                                 00.hogepiyohogepiyohogepiyohogepiyo.txt

~/Desktop/ruby-practices feature/ls3*
❯ ruby 04.ls/ls.rb -ra アイウエオ.txt .
アイウエオ.txt

.:
アイウエオ.txt  98.rake            01.fizzbuzz
あいうえお.txt  07.ls_object       00.hogepiyohogepiyohogepiyohogepiyo.txt
aAあア.txt      06.bowling_object  00.hoge.txt
README.md       05.wc              .rubocop.yml
Gemfile.lock    04.ls              .gitignore
Gemfile         03.bowling         .git
99.wc_object    02.calendar
```

2023-01-26 15:58 UTC, u1tnk requested changes

2023-01-26 15:58 UTC, u1tnk commented on 04.ls/ls.rb
> +def exec_option_a(files_in_directory)
オプションxxxの処理というメソッド名は良くないです。以下のような理由です。

- (プラクティスの範囲で問題は起きないですが) この部分の動作に関わるオプションが追加されたり、複合オプション(xを指定すると alr全部の効果になるとか)ができると詰みます。
- オプションはソートするとか収集するとかの動作をカスタマイズするものなので、「ソートする」「収集する」という主要な動作が名前からなくなってしまっています。

2023-01-26 15:58 UTC, u1tnk commented on 04.ls/ls.rb
> +      match_ja = file_path.match(/[ぁ-んァ-ヶ一-龠]+/).to_s
2バイト文字は日本語だけでも無いので、分かりませんが、おそらくは他にもあると思うのでこの条件はよくないであす。
2バイト幅の文字の判別可能とは思いますが、プラクティスの必須項目でも無いので、ファイル名は2バイト文字使わない前提で大丈夫です 🙆‍♀️

2023-01-29 04:01 UTC, koyama-c commented on 04.ls/ls.rb
> +      match_ja = file_path.match(/[ぁ-んァ-ヶ一-龠]+/).to_s
ご指摘の通り中途半端な条件でしたので今回は2バイト文字を含むファイル名がないことを前提としたいと思います。

2023-01-29 04:01 UTC, koyama-c commented on 04.ls/ls.rb
> +def exec_option_a(files_in_directory)
確かにaオプションが指定された時の処理に対して「オプション」という言葉は抽象的でしたので、具体的にメソッドの動作を表すような名前に変更しました。
`exclude_hidden_file` → 隠しファイルを含まない
`include_hidden_file` → 隠しファイルを含む

また、オプションごとにどのようなファイルを表示するかの制御は`apply_option`という名前で定義しました。

2023-01-29 14:17 UTC, u1tnk commented on 04.ls/ls.rb
> +def exec_option_a(files_in_directory)
確かにちょっと意図が違いましたね。

多少違っても良い方向なら大丈夫ですが、 `apply_option` はちょっと厳しいです。
このプラクティスの範囲でも `-l`が追加されると `apply_option`の組み合わせが増えて厳しくなりますし、オプションは適宜追加されていくものなので追加が容易である必要があるからです。

元のコメントの意図としては 

> オプションはソートするとか収集するとかの動作をカスタマイズするものなので、「ソートする」「収集する」という主要な動作が名前からなくなってしまっています。

にあるとおり 「ソートする」、「収集する」という役割のメソッドにして関係のあるオプションを渡して、メソッド内で動作を変えるという意図でしたが伝わりますでしょうか？

2023-02-01 13:49 UTC, koyama-c commented on 04.ls/ls.rb
> +def exec_option_a(files_in_directory)
@u1tnk 
> このプラクティスの範囲でも -lが追加されると apply_optionの組み合わせが増えて厳しくなる

おっしゃるように組み合わせがどんどん増えていって`apply_option `メソッドで条件分岐するのには限界が来そうでした....

> メソッド内で動作を変える

mainメソッド内でオプションによって動作を変えるようにしました。
```
    # files_for_display は出力対象のファイル

    results_considering_hidden_file = @option['a'] ? include_hidden_file(file_path) : exclude_hidden_file(file_path)
    files_for_display = @option['r'] ? results_considering_hidden_file.reverse : results_considering_hidden_file
```

2023-02-01 16:57 UTC, u1tnk requested changes

2023-02-01 16:57 UTC, u1tnk commented on 04.ls/ls.rb
> +    results_considering_hidden_file = @option['a'] ? include_hidden_file(file_path) : exclude_hidden_file(file_path)
この変数名は長いですし、hiddenが入るかどうかもオプションによりますし、resultsもあまり情報が無いので `files`で良いと思います。

2023-02-01 20:49 UTC, koyama-c commented on 04.ls/ls.rb
> +    results_considering_hidden_file = @option['a'] ? include_hidden_file(file_path) : exclude_hidden_file(file_path)
隠しファイルを考慮した結果というつもりだったんですが、ご指摘の通りだったので修正しました。

2023-02-02 22:55 UTC, merged