lsコマンドを作る4
ckym02/ruby-practices pull request #7
Opened 2023-02-04 14:14 UTC by koyama-c

2023-02-08 15:14 UTC, u1tnk requested changes

2023-02-08 15:14 UTC, u1tnk commented on 04.ls/ls.rb
> +def print_files_details(file_path, files_for_display)
`file_path` というと `/xxx/yyyy/zzz.rb`みたいなパスの場合もあるので `directory_path`の方が分かりやすいかなと思います。

2023-02-08 15:14 UTC, u1tnk commented on 04.ls/ls.rb
> +def enum(role)
enum は一般的な名称なのでちょっとふさわしく無いメソッド名ですね。
また こういうデータ定義部分は 定数を作った方が見やすくなるのでやってみてください 💪

2023-02-08 15:14 UTC, u1tnk commented on 04.ls/ls.rb
> +  select_directory.each do |file_path|
ここから file_pathじゃなくて directory_pathが良さそうですね。

2023-02-08 15:14 UTC, u1tnk commented on 04.ls/ls.rb
> +    stat = File.stat("#{file_path}/#{file}")
File.statはファイルアクセスを伴うので他と比較すると低速な処理です。
calc_max_lengthが4回呼ばれているので10ファイルあるとしてもこの処理が40回呼ばれるのでファイル数が増えると現実的に遅くなると思うので改善しましょう。

一つのファイルに対して File.statを実行するのは一回になるように改善してみてください 💪

2023-02-08 19:41 UTC, koyama-c commented on 04.ls/ls.rb
> +def enum(role)
関数にする必要はなさそうでしたので、ハッシュを定数として定義するように修正しました！

2023-02-08 19:42 UTC, koyama-c commented on 04.ls/ls.rb
> +def print_files_details(file_path, files_for_display)
なるほど！ファイルパスとディレクトリパスを意識せずに実装していました 😓 
勉強になります。修正しました！

2023-02-08 19:43 UTC, koyama-c commented on 04.ls/ls.rb
> +  select_directory.each do |file_path|
こちらも修正しました 🙏

2023-02-08 19:45 UTC, koyama-c commented on 04.ls/ls.rb
> +    stat = File.stat("#{file_path}/#{file}")
calc_max_length で ハッシュを返していたのを忘れていました。File.statを1回実行して戻り値を変数`max_length`に入れてそれをみるようにしました。

2023-02-09 12:44 UTC, u1tnk requested changes
`calc_max_length` 内の `File.stat`の件ですが、 確かに改善前より1/4にはなっているのですが、一つのファイルごとに全ファイル分実行していて ファイル数の二乗回実行しているのでまだNGです。
    そもそもFile.statだけの話ではなく、 calc_max_length自体も一回の実行で良いはずですね(これは前回指摘しておけば良かったです。すみません🙏 )

2023-02-09 19:00 UTC, koyama-c commented
ファイル数×2回（列を揃えるため文字列の最大を求めるためにファイル数回実行 + 実際にファイル情報を出力するためにファイル数回実行）`File.stat`が実行されるように修正しました。
度々お手数おかけしますがご確認お願いします 🙇

2023-02-10 00:48 UTC, u1tnk approved these changes
コメントしてくれた通り、totalの計算も冗長ではありますが 実行回数はO(n)で済んだので良しとします。元は O(n^2) だったので。
業務でデータ数が多めのときに重い処理(例えばDB接続やファイルアクセス)がO(n^2)だと絶対NGなので覚えてもらおうと思いました。やらかすとサーバ落ちたり、毎日実行するバッチの実行時間が24時間超えたりしたのも見た事あります😅 

理想を言うと File.stat使ってデータをファイルごとに取る処理を最初に実行して、それ以後はそれを使いまわすようにすれば File.statは一回で済みますね。
LSコマンドはオブジェクト指向版でしっかりリファクタリング(再構築)するこになるのでそこでは一回で済むように意識してやってもらえれば良いと思います。

2023-02-10 11:02 UTC, merged